### ISSUE TITLE
CALF_Calibration_GCN: Code & RuntimeError

### ISSUE THREAD

**Issue by rorybunker** [SoccerNet/sn-spotting#12]
I am trying to run CALF_Calibration_GCN [https://github.com/SoccerNet/sn-spotting/tree/main/Benchmarks/CALF_Calibration_GCN](url) to replicate the Benchmark results.
In your code to run this model, model_name is specified twice. I presume the second, `--model_name=calib_GCN_run_${i}`, is redundant here?:
```
python src/main.py \
--SoccerNet_path=path/to/SoccerNet/ \
--features=ResNET_TF2_PCA512.npy \
--num_features=512 \
--model_name=calib_GCN \
--batch_size 32 \
--evaluation_frequency 20 \
--chunks_per_epoch 18000 \
--model_name=calib_GCN_run_${i}  \
--backbone_feature=2DConv \
--backbone_player=resGCN-14 \
--dist_graph_player=25 \
--calibration \
--feature_multiplier 2 \
--class_split visual 
```

Also, even if this line is removed, I keep getting `RuntimeError: CUDA out of memory.`
I have tried reducing batch_size from 32 to 16 and running the model on a server node with a greater number of GPUs, but without success.
Do you have any suggestions as to how I can prevent this error?

**Comment by SilvioGiancola** [comment]
What GPU are you using? You simply do not have enough memory in your GPU. Please refer to the paper for more details on how that model was trained. Thanks.
