### ISSUE TITLE
Possible OOM issue in training for NetVLAD++ (Linux Ubuntu 18.04)

### ISSUE THREAD

**Issue by mumulmaulana** [SoccerNet/sn-spotting#14]
Hello!
Thank you so much for providing this open repository for everyone!

I would like to ask about my issue running training for the Benchmark model.
I tried training for the NetVLAD++ benchmark model in my system and ran into this issue:
![Screenshot from 2023-08-04 11-37-33](https://github.com/SoccerNet/sn-spotting/assets/15167519/6459250c-b959-4c27-9d48-ed610477e9f5)

This is the parameters for the training:

> 2023-08-04 11:16:14,511 [MainThread  ] [INFO ]  Parameters:
> 2023-08-04 11:16:14,511 [MainThread  ] [INFO ]   SoccerNet_path : /media/ogatalab/SSD-PGU3C/SoccerNet
> 2023-08-04 11:16:14,511 [MainThread  ] [INFO ]         features : ResNET_TF2.npy
> 2023-08-04 11:16:14,511 [MainThread  ] [INFO ]       max_epochs : 1000
> 2023-08-04 11:16:14,511 [MainThread  ] [INFO ]     load_weights : None
> 2023-08-04 11:16:14,511 [MainThread  ] [INFO ]       model_name : NetVLAD++
> 2023-08-04 11:16:14,511 [MainThread  ] [INFO ]        test_only : False
> 2023-08-04 11:16:14,511 [MainThread  ] [INFO ]      split_train : ['train']
> 2023-08-04 11:16:14,511 [MainThread  ] [INFO ]      split_valid : ['valid']
> 2023-08-04 11:16:14,511 [MainThread  ] [INFO ]       split_test : ['test', 'challenge']
> 2023-08-04 11:16:14,511 [MainThread  ] [INFO ]          version : 2
> 2023-08-04 11:16:14,511 [MainThread  ] [INFO ]      feature_dim : None
> 2023-08-04 11:16:14,511 [MainThread  ] [INFO ]  evaluation_frequency : 10
> 2023-08-04 11:16:14,511 [MainThread  ] [INFO ]        framerate : 2
> 2023-08-04 11:16:14,511 [MainThread  ] [INFO ]      window_size : 15
> 2023-08-04 11:16:14,511 [MainThread  ] [INFO ]             pool : NetVLAD++
> 2023-08-04 11:16:14,511 [MainThread  ] [INFO ]       vocab_size : 64
> 2023-08-04 11:16:14,511 [MainThread  ] [INFO ]       NMS_window : 30
> 2023-08-04 11:16:14,511 [MainThread  ] [INFO ]    NMS_threshold : 0.0
> 2023-08-04 11:16:14,511 [MainThread  ] [INFO ]       batch_size : 256
> 2023-08-04 11:16:14,511 [MainThread  ] [INFO ]               LR : 0.001
> 2023-08-04 11:16:14,511 [MainThread  ] [INFO ]              LRe : 1e-06
> 2023-08-04 11:16:14,511 [MainThread  ] [INFO ]         patience : 10
> 2023-08-04 11:16:14,511 [MainThread  ] [INFO ]              GPU : 0
> 2023-08-04 11:16:14,511 [MainThread  ] [INFO ]   max_num_worker : 4
> 2023-08-04 11:16:14,511 [MainThread  ] [INFO ]             seed : 0
> 2023-08-04 11:16:14,511 [MainThread  ] [INFO ]         loglevel : INFO

I have tried to reduce the batch_size and max_num_workers as well, but the problem persists.
Also, not sure if it is needed, but it seems it only happens after it runs the test() procedure.

I found no trouble training with PCA512 features, so I figure there must be some resource issues.
When I look at the System Monitor and GPU usage, this is the reading of the result.
![Screenshot from 2023-08-03 16-18-17](https://github.com/SoccerNet/sn-spotting/assets/15167519/9c2b7c72-0551-405f-a038-93f7d0e61185)

I have tried increasing the swap file to more than 64GB, but it only results in my system freezing and crashing.
Are you familiar with this issue? Is there any way for me to bypass this?
Or, if it is no trouble, can you tell me the recommended specification to run this training?
Thank you!

My system specs (RAM 16GB, SSD 2TB):
1. CPU

> Architecture:        x86_64
> CPU op-mode(s):      32-bit, 64-bit
> Byte Order:          Little Endian
> CPU(s):              6
> On-line CPU(s) list: 0-5
> Thread(s) per core:  1
> Core(s) per socket:  6
> Socket(s):           1
> NUMA node(s):        1
> Vendor ID:           AuthenticAMD
> CPU family:          23
> Model:               113
> Model name:          AMD Ryzen 5 3500 6-Core Processor
> Stepping:            0
> CPU MHz:             3266.777
> CPU max MHz:         3600.0000
> CPU min MHz:         2200.0000
> BogoMIPS:            7186.49
> Virtualization:      AMD-V
> L1d cache:           32K
> L1i cache:           32K
> L2 cache:            512K
> L3 cache:            8192K
> NUMA node0 CPU(s):   0-5

2. GPU (NVIDIA GeForce RTX 3060 Ti)

> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 470.182.03   Driver Version: 470.182.03   CUDA Version: 11.4     |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |                               |                      |               MIG M. |
> |===============================+======================+======================|
> |   0  NVIDIA GeForce ...  Off  | 00000000:06:00.0  On |                  N/A |
> | 30%   51C    P2    57W / 200W |   2270MiB /  7973MiB |      0%      Default |
> |                               |                      |                  N/A |
> +-------------------------------+----------------------+----------------------+
>                                                                                
> +-----------------------------------------------------------------------------+
> | Processes:                                                                  |
> |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
> |        ID   ID                                                   Usage      |
> |=============================================================================|
> |    0   N/A  N/A      1067      G   /usr/bin/gnome-shell               87MiB |
> |    0   N/A  N/A      1431      G   /usr/lib/xorg/Xorg                146MiB |
> |    0   N/A  N/A      1546      G   /usr/bin/gnome-shell               46MiB |
> |    0   N/A  N/A      2130      G   ...RendererForSitePerProcess       87MiB |
> |    0   N/A  N/A      2754      G   /usr/bin/nvidia-settings            0MiB |
> |    0   N/A  N/A      5116      C   python                           1809MiB |
> |    0   N/A  N/A     23313      G   ...464382835143902905,262144       77MiB |
> +-----------------------------------------------------------------------------+

**Comment by SilvioGiancola** [comment]
Hi @mumulmaulana ,
Your issue most probably originates from your RAM; you don't have enough to pre-load all the ResNET features with dimension 2048. I ran my experiments on a workstation with 256GB of RAM, which could also accommodate the Baidu features of even larger dimensions (~8k AFAIK). The PCA512 version are reduced to a dimension of 512 with PCA, which consumes less RAM for fairly similar performances.

A solution for you would be to update the dataset class to load the features when sampling them in `__getitem__`, instead of pre-loading them all on `__init__`.

I hope that helps!

**Comment by mumulmaulana** [comment]
Thanks for responding!
I will try the workaround first and get back with the result!
