### ISSUE TITLE
Cannot download data for spotting-ball-2024 (HTTP Error 401: Unauthorized)

### ISSUE THREAD

**Issue by druefena** [SoccerNet/sn-spotting#16]
As suggested in the title, I am unable to download the action spotting dataset for the 2024 challenge. I get a 'HTTP Error 401: Unauthorized'. I tried using the 'download_ball_data.py' from the official repo, inputting the password provided after signing the NDA, using both python 3.9 and 3.10.

Can you please advise what to do here?

**Comment by druefena** [comment]
Just as a follow-up, I am able to download the `spotting-ball-2023` dataset, so there must be something not quite right with the 2024 version. As I understand, only the labels have changed, not the videos, so would be great if there were an option to just download the labels.

**Comment by SilvioGiancola** [comment]
Hi @druefena , please give it a try now. We just made the links for the data public right now. Thanks

**Comment by druefena** [comment]
Hi @SilvioGiancola , thanks for the quick reply. Unfortunately I am still getting the same error for the `spotting-ball-2024` dataset.

**Comment by SilvioGiancola** [comment]
@cioppaanthony are you able to download the dataset on your end? On my side it's working fine: 
<img width="1400" alt="image" src="https://github.com/SoccerNet/sn-spotting/assets/7395008/48988649-addc-4a04-8ee8-4838aa166f32">

**Comment by druefena** [comment]
Ok, figured out the issue. One should not provide a password, then the download works.

So some setting must be wrong, and the instructions (as well as the provided `download_ball_data.py` script) does not work as provided.

**Comment by SilvioGiancola** [comment]
My bad, you actually need the password for the NDA :) Big sorry for the confusion!

Please follow these instructions: https://github.com/SoccerNet/sn-spotting?tab=readme-ov-file#soccernet-ball-action-spotting

Thanks for "spotting" the mistake ;)
