### ISSUE TITLE
Multiple GPU usage

### ISSUE THREAD

**Issue by Tortoise17** [SoccerNet/sn-spotting#5]
Is it possible to use the multi GPU with the routine available? with shared memory ?

**Comment by SilvioGiancola** [comment]
The only work I am aware of that used 16 v100 (DGX-1) is:
Automated Event Detection and Classification in Soccer: The Potential of Using Multiple Modalities
https://scholar.google.com/scholar?q=Automated+Event+Detection+and+Classification+in+Soccer:+The+Potential+of+Using+Multiple+Modalities&hl=en&as_sdt=0&as_vis=1&oi=scholart

**Comment by Tortoise17** [comment]
@SilvioGiancola  thank you.
