### ISSUE TITLE
Baidu feats extractor

### ISSUE THREAD

**Issue by Tortoise17** [SoccerNet/sn-spotting#7]
Is there any feature extractor routine available for baidu embeddings ? How these features are extracted?

**Comment by SilvioGiancola** [comment]
We are not the authors of those embeddings, that were generated by Baidu Vidpress. Have a look at their repository [https://github.com/baidu-research/vidpress-sports](https://github.com/baidu-research/vidpress-sports) and please raise your concerns to Baidu Vidpress directly. Thanks.
