### ISSUE TITLE
ABOUT CVPR22 SUBMISSION

### ISSUE THREAD

**Issue by rogercmq** [SoccerNet/sn-spotting#8]
Hi, i am wondering when will the cvpr22 evaluation server be ready. 

I have just participated in this challenge and I find that there is no submission page on EvalAI. 

By the way, are challenge set games included in Baidu features? Thx.

**Comment by SilvioGiancola** [comment]
Hi @rogercmq , the CVPR22 evaluation server is up and running: https://eval.ai/web/challenges/challenge-page/1536/overview
That information was missing in this github repository.

And yes, we provide the Baidu features for the games of the challenge set.

**Comment by rogercmq** [comment]
Got it. Thanks!
